// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZvkc5mqJAqFfGsDCe-DCufd__QdLr9xk',
    appId: '1:564684720924:web:0f5a6e71de5d0945eac8d9',
    messagingSenderId: '564684720924',
    projectId: 'combustible-7dca6',
    authDomain: 'combustible-7dca6.firebaseapp.com',
    storageBucket: 'combustible-7dca6.appspot.com',
    measurementId: 'G-753VF6N7ZS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBATJ94k_FnDgwqan2-YdxMmoiv5fHyvic',
    appId: '1:564684720924:android:9e3a77df83ec3488eac8d9',
    messagingSenderId: '564684720924',
    projectId: 'combustible-7dca6',
    storageBucket: 'combustible-7dca6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBGnmdS6PeCkL08FR2Z8uTdlynIrh9Za4',
    appId: '1:564684720924:ios:239978ebceb7e29eeac8d9',
    messagingSenderId: '564684720924',
    projectId: 'combustible-7dca6',
    storageBucket: 'combustible-7dca6.appspot.com',
    iosBundleId: 'com.conysis.combustible.plantilla',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBGnmdS6PeCkL08FR2Z8uTdlynIrh9Za4',
    appId: '1:564684720924:ios:239978ebceb7e29eeac8d9',
    messagingSenderId: '564684720924',
    projectId: 'combustible-7dca6',
    storageBucket: 'combustible-7dca6.appspot.com',
    iosBundleId: 'com.conysis.combustible.plantilla',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZvkc5mqJAqFfGsDCe-DCufd__QdLr9xk',
    appId: '1:564684720924:web:bfba5504863906b6eac8d9',
    messagingSenderId: '564684720924',
    projectId: 'combustible-7dca6',
    authDomain: 'combustible-7dca6.firebaseapp.com',
    storageBucket: 'combustible-7dca6.appspot.com',
    measurementId: 'G-B6X2TF917X',
  );
}
